version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.prod
    container_name: backend-dev
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./backend/data:/app/backend/data
      - /opt/cognisphere/config/application.properties:/app/config/application.properties
    restart: always
    depends_on:
      neo4j:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: frontend-dev
    restart: always
    ports:
      - "80:80"

  neo4j:
    image: neo4j:5.15
    container_name: neo4j-dev
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/test123123
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
    healthcheck:
      test: [ "CMD-SHELL", "echo 'healthcheck passed'" ]
      interval: 30s
      timeout: 10s
      retries: 5

